# Generated by Django 5.0 on 2023-12-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='card',
            name='style',
            field=models.CharField(default='bg-gray-100', max_length=255),
        ),
    ]
