# Generated by Django 5.0 on 2024-01-05 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_options_card_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 20, 31, 46, 262772, tzinfo=datetime.timezone.utc)),
        ),
    ]
