# Generated by Django 5.0 on 2024-01-05 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_calendar_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='available_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
