# Generated by Django 5.0 on 2024-01-16 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_calendar_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
